### ISSUE TITLE
Review 1

### ISSUE THREAD

**Issue by so2niko** [D-mezentseff/Whatwhithrockets#1]
- [x] Объявление строки

https://github.com/D-mezentseff/Whatwhithrockets/blob/e5bdc6a8a6eb1c0718d1332e363e66972824d538/hw_02/app/main.js#L54
__________________

- [x] Точки с запятой
https://github.com/D-mezentseff/Whatwhithrockets/blob/e5bdc6a8a6eb1c0718d1332e363e66972824d538/hw_02/app/main.js#L54
https://github.com/D-mezentseff/Whatwhithrockets/blob/e5bdc6a8a6eb1c0718d1332e363e66972824d538/hw_02/app/main.js#L55
________________________

- [x] Не мутирующий метод
```js
str.toString()
```

**Comment by D-mezentseff** [comment]
Edit miatkes
